[project]
name = "notetime"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "newsflash>=0.2.1",
    "pydantic>=2.12.5",
    "pytest>=9.0.2",
]

[dependency-groups]
dev = [
    "ruff>=0.14.14",
]
